### ISSUE TITLE
Labo 02 - Migration Mariadb to Aurora

### ISSUE THREAD

**Issue by NicolasGlassey** [heig-lherman/cld#1]
@Lutonite  @Mystere98 

As per your request, I give you my agreement to adapt the lab02 and migrate to Aurora.

Enjoy !

**Comment by Lutonite** [comment]
Hello,

We decided against using Aurora as it required us setting up a cluster instead of a simple instance, which is more of an inconvenience than a problem. However, T-class aurora instances have to be t3.medium at the minimum, which we thought would probably incur higher costs than necessary.
